"""update

Revision ID: 166deb25ae65
Revises: f0de2329d599
Create Date: 2025-09-07 14:30:38.028088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166deb25ae65'
down_revision: Union[str, Sequence[str], None] = 'f0de2329d599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_sequences',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_unique_constraint(None, 'orders', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_table('order_sequences')
    # ### end Alembic commands ###
