"""update

Revision ID: 6713b1352593
Revises: a6772c4e28fd
Create Date: 2025-09-06 09:33:32.675217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6713b1352593'
down_revision: Union[str, Sequence[str], None] = 'a6772c4e28fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address_2', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('suburb', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('state', sa.String(length=255), nullable=True))
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'suburb')
    op.drop_column('customers', 'address_2')
    # ### end Alembic commands ###
