"""update

Revision ID: be57db141b9b
Revises: 061f90d517b9
Create Date: 2025-09-05 16:50:52.865594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be57db141b9b'
down_revision: Union[str, Sequence[str], None] = '061f90d517b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'receiver_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('orders', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    op.alter_column('customers', 'receiver_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
