"""update

Revision ID: ffc854b1b4a2
Revises: beddd165dd54
Create Date: 2025-09-06 16:06:44.480354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc854b1b4a2'
down_revision: Union[str, Sequence[str], None] = 'beddd165dd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address_2', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('suburb', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('post_code', sa.String(), nullable=True))
    op.alter_column('orders', 'receiver_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'receiver_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('orders', 'post_code')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'suburb')
    op.drop_column('orders', 'address_2')
    # ### end Alembic commands ###
